/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppModal: typeof import('./src/components/AppModal.vue')['default']
    AppSelect: typeof import('./src/components/AppSelect.vue')['default']
    CommandModal: typeof import('./src/components/modals/CommandModal.vue')['default']
    DeleteConfirmModal: typeof import('./src/components/modals/DeleteConfirmModal.vue')['default']
    Dock: typeof import('./src/components/Dock.vue')['default']
    FileModal: typeof import('./src/components/modals/FileModal.vue')['default']
    InstallPreviewModal: typeof import('./src/components/modals/InstallPreviewModal.vue')['default']
    MappingModal: typeof import('./src/components/modals/MappingModal.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NProgress: typeof import('naive-ui')['NProgress']
    NSelect: typeof import('naive-ui')['NSelect']
    NVirtualList: typeof import('naive-ui')['NVirtualList']
    ShortcutRecordModal: typeof import('./src/components/modals/ShortcutRecordModal.vue')['default']
    SshHostModal: typeof import('./src/components/modals/SshHostModal.vue')['default']
    TerminalModal: typeof import('./src/components/modals/TerminalModal.vue')['default']
  }
}
